### ISSUE TITLE
Why so many emojis?!?!

### ISSUE THREAD

**Issue by deniscostadsc** [PauloLuan/playground#1]
![Screen Shot 2021-06-10 at 13 16 50](https://user-images.githubusercontent.com/358777/121560746-31cf4a00-c9ee-11eb-9f77-1695b0771a76.png)

**Comment by PauloLuan** [comment]
@deniscostadsc because I've configured some aliases on my terminal:

![image](https://user-images.githubusercontent.com/1131963/121695344-5a644c00-caa1-11eb-897d-82d82ad34551.png)

**Comment by PauloLuan** [comment]
@deniscostadsc I miss you buddie! how have you been? (👉 with 💅 a 💪 lot 🤝 of 👌 emojis 👈)

**Comment by deniscostadsc** [comment]
Hi ✋🏾 

I'm doing great 🤙🏾. I'm isolated at home with my family 👪. I'm now working at that purple bank 🟪 🏦. Also miss you bro 🤗!
